//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateTourNotebook.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealEstateTourNotebook.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real Estate Tour Notebook is an indispensable support to your estate visits. When you visit , you may notice the points that looks interesting and then you can compare the different visits to find the best choice.
        ///
        ///John-William Forcier.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Place.
        /// </summary>
        public static string AddNear {
            get {
                return ResourceManager.GetString("AddNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent Repairs.
        /// </summary>
        public static string AddRecentRepair {
            get {
                return ResourceManager.GetString("AddRecentRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à todo Repair.
        /// </summary>
        public static string AddRepairs {
            get {
                return ResourceManager.GetString("AddRepairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string AllEstateType {
            get {
                return ResourceManager.GetString("AllEstateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string AllTourType {
            get {
                return ResourceManager.GetString("AllTourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apartment.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real Estate Tour Notebook.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply Filter.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Permanent Residence.
        /// </summary>
        public static string BuyForHome {
            get {
                return ResourceManager.GetString("BuyForHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rental Investment.
        /// </summary>
        public static string BuyForInvestment {
            get {
                return ResourceManager.GetString("BuyForInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose Picture.
        /// </summary>
        public static string ChoosePicture {
            get {
                return ResourceManager.GetString("ChoosePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Condominium.
        /// </summary>
        public static string Condominium {
            get {
                return ResourceManager.GetString("Condominium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tour Date.
        /// </summary>
        public static string DateTour {
            get {
                return ResourceManager.GetString("DateTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RealEstateNotebook.sdf.
        /// </summary>
        public static string DBFileName {
            get {
                return ResourceManager.GetString("DBFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit Tour.
        /// </summary>
        public static string EditTour {
            get {
                return ResourceManager.GetString("EditTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checklist.
        /// </summary>
        public static string EstateCheckList {
            get {
                return ResourceManager.GetString("EstateCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Estate Type.
        /// </summary>
        public static string EstateType {
            get {
                return ResourceManager.GetString("EstateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter By :.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à filter.
        /// </summary>
        public static string Filtrer {
            get {
                return ResourceManager.GetString("Filtrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5 1/2.
        /// </summary>
        public static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sq.ft.
        /// </summary>
        public static string FootSquare {
            get {
                return ResourceManager.GetString("FootSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4 1/2.
        /// </summary>
        public static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to....
        /// </summary>
        public static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heating Price.
        /// </summary>
        public static string HeatingPrice {
            get {
                return ResourceManager.GetString("HeatingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hold finger down on map to locate the place.
        /// </summary>
        public static string HoldFinger {
            get {
                return ResourceManager.GetString("HoldFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dashboard.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à House.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No result found for : {0}.
        /// </summary>
        public static string InvalideSearch {
            get {
                return ResourceManager.GetString("InvalideSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Land.
        /// </summary>
        public static string Land {
            get {
                return ResourceManager.GetString("Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light / Ambiance.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Tours.
        /// </summary>
        public static string ListTour {
            get {
                return ResourceManager.GetString("ListTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Make sure you have activated your location..
        /// </summary>
        public static string LocationError {
            get {
                return ResourceManager.GetString("LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Checklist.
        /// </summary>
        public static string MyChecklist {
            get {
                return ResourceManager.GetString("MyChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Notebook.
        /// </summary>
        public static string MyNotebook {
            get {
                return ResourceManager.GetString("MyNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Position.
        /// </summary>
        public static string MyPosition {
            get {
                return ResourceManager.GetString("MyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Tour.
        /// </summary>
        public static string MyTour {
            get {
                return ResourceManager.GetString("MyTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Near of : .
        /// </summary>
        public static string NearOf {
            get {
                return ResourceManager.GetString("NearOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Neighborhood quality (noise, traffic , parking, pets , etc ).
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Tour.
        /// </summary>
        public static string NewTour {
            get {
                return ResourceManager.GetString("NewTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 1/2.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other notes.
        /// </summary>
        public static string OtherNotes {
            get {
                return ResourceManager.GetString("OtherNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other pictures.
        /// </summary>
        public static string OtherPictures {
            get {
                return ResourceManager.GetString("OtherPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Owner&apos;s Name (or Agency).
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à / Month.
        /// </summary>
        public static string PerMonth {
            get {
                return ResourceManager.GetString("PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rate this app.
        /// </summary>
        public static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent Repairs.
        /// </summary>
        public static string RecentRepairs {
            get {
                return ResourceManager.GetString("RecentRepairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rent.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repairs.
        /// </summary>
        public static string Repairs {
            get {
                return ResourceManager.GetString("Repairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to restart.
        /// </summary>
        public static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à select.
        /// </summary>
        public static string SelectTour {
            get {
                return ResourceManager.GetString("SelectTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7 1/2 +.
        /// </summary>
        public static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6 1/2.
        /// </summary>
        public static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3 1/2.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TODO :.
        /// </summary>
        public static string TODO {
            get {
                return ResourceManager.GetString("TODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2 1/2.
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unit of distance.
        /// </summary>
        public static string UnitDistance {
            get {
                return ResourceManager.GetString("UnitDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unit of dimension.
        /// </summary>
        public static string UnitMeasurement {
            get {
                return ResourceManager.GetString("UnitMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Year of construction.
        /// </summary>
        public static string YearBuilt {
            get {
                return ResourceManager.GetString("YearBuilt", resourceCulture);
            }
        }
    }
}
